[toolchain]
channel = "stable"
components = [
    "rust-analyzer",
    "rust-src",
    "rustc-codegen-cranelift-preview",
    "rustfmt",
]
targets = [
    "x86_64-unknown-linux-gnu",
    "wasm32-unknown-unknown"
]
