# Ensures that resources are in place before bundling will take place
[[hooks]]
stage = "pre_build"    # When to run hook, must be one of "pre_build", "build", "post_build"
command = "cargo"      # Command to run
command_arguments = [  # Arguments to pass to command
    "check",
]

[serve]
port = 8000

[watch]
watch = [
    "src",
    "../forge",
    "../libs"
]

[build]
release = false