[package]
name = "leptos_forge"
version.workspace = true
edition.workspace = true
readme = "../README.md"
build="src/rust/build/build.rs"

[lib]
path = "src/rust/main/lib.rs"

[dependencies]
leptos = { workspace = true, features = ["csr"] }
leptos_axum = { workspace = true, optional = true }
leptos_meta.workspace = true
leptos-node-ref.workspace = true
leptos_router.workspace = true
leptos-use.workspace = true
reactive_stores.workspace = true
send_wrapper.workspace = true
js-sys.workspace = true

utils_leptos.workspace = true 

ui_components.workspace = true
ui_layout.workspace = true

cfg-if.workspace = true
console_log.workspace = true
console_error_panic_hook.workspace = true
http.workspace = true
log.workspace = true
testing-library-dom.workspace = true
thiserror.workspace = true
uuid.workspace = true

[features]
default = []
hydrate = [
    "leptos/hydrate",
    "utils_leptos/hydrate"
]
ssr = [
    "leptos/ssr", 
    "leptos_meta/ssr", 
    "leptos_router/ssr", 
    "utils_leptos/ssr",
    "dep:leptos_axum"
]

[lints]
workspace = true

[target.wasm32-unknown-unknown]
rustflags = [
   "--cfg",
   "erase_components",
]