[package]
name = "leptos_forge"
version.workspace = true
edition.workspace = true
readme = "../README.md"
build="src/rust/build/build.rs"
include = [
    "src/css/forge.css",
    "src/resources/generated/leptos-forge.css",
    "src/resources/logo/logo.svg"
]

[lib]
path = "src/rust/main/lib.rs"

[dependencies]
leptos = { workspace = true, features = ["csr"] }
leptos_router.workspace = true
reactive_stores.workspace = true

utils_leptos.workspace = true 

ui_components.workspace = true
ui_layout.workspace = true

[features]
default = []

[lints]
workspace = true

[package.metadata.cargo_resources]
provides = [
    { crate_path = "src/resources/generated/leptos-forge.css", output_path="leptos_forge.css" },
    { crate_path = "src/css/main/forge.css", output_path="leptos_forge/common.css"},
    { crate_path = "src/resources/logo/logo.svg", output_path="leptos_forge/logo/logo.svg" }
]