//! Strategies related to vectors
//!

use std::ops::Range;

use proptest::prelude::*;

/// Generates a vector of vectors of elements generated by value strategy
pub fn vec_of_vec<S: Strategy + 'static>(
    outer: Range<usize>,
    inner: Range<usize>,
    value: S,
) -> BoxedStrategy<Vec<Vec<<S as Strategy>::Value>>> {
    prop::collection::vec(prop::collection::vec(value, inner), outer).boxed()
}
